backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create in {{collection}} {{slug}} post'
    update: 'Update in {{collection}} {{slug}} post'
    delete: 'Delete in {{collection}} {{slug}} post'

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - label: "Blog"
    name: "blog"
    folder: "src/pages/blog-data"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "path", widget: "hidden", default: "blog-post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Author", name: "author", widget: "string" }